services:
  mysql:
    image: mysql:8.0
    container_name: trinity_mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trinity
      MYSQL_USER: trinity
      MYSQL_PASSWORD: trinity
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
