"""add payloads column to llm_executions

Revision ID: 1cca30299a20
Revises: f8a9b2c3d4e5
Create Date: 2026-09-02 14:17:28.127720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cca30299a20'
down_revision = 'f8a9b2c3d4e5'
branch_labels = None
depends_on = None


# English comments inside code
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('llm_execution_steps', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstepstatus'),
               type_=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstepstatus'),
               existing_nullable=False)

    with op.batch_alter_table('llm_executions', schema=None) as batch_op:
        # Add server_default='{}' to ensure existing rows get a valid empty JSON payload in SQLite
        batch_op.add_column(
            sa.Column(
                'payloads', 
                sa.JSON(), 
                nullable=False, 
                server_default=sa.text("'{}'")
            )
        )

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('llm_executions', schema=None) as batch_op:
        batch_op.drop_column('payloads')

    with op.batch_alter_table('llm_execution_steps', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstepstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('datasources', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
