"""add llm_executions table

Revision ID: 1ce3170726bf
Revises: d7cc7e7e5c5e
Create Date: 2026-07-27 10:49:05.600011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce3170726bf'
down_revision = 'd7cc7e7e5c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('response_type', sa.String(length=50), nullable=False),
    sa.Column('summary_or_content', sa.Text(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_executions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_executions_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_executions_message_id'))
        batch_op.drop_index(batch_op.f('ix_llm_executions_conversation_id'))

    op.drop_table('llm_executions')
    # ### end Alembic commands ###
