"""add thoughts column to messages

Revision ID: 312337e1380d
Revises: 53d58ed9451d
Create Date: 2026-09-22 11:38:32.069315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '312337e1380d'
down_revision = '53d58ed9451d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thoughts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('thoughts')

    # ### end Alembic commands ###
