"""add message_thoughts table and sequence_index to llm_executions

Revision ID: 6f86df4857fc
Revises: 312337e1380d
Create Date: 2026-09-23 12:00:12.793336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f86df4857fc'
down_revision = '312337e1380d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_thoughts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False, server_default="0"),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_thoughts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_thoughts_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('llm_executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence_index', sa.Integer(), nullable=False, server_default="0"))

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.alter_column('file_path',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('mime_type',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conv_timestamp'))
        batch_op.drop_column('thoughts')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thoughts', sa.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_conv_timestamp'), ['conversation_id', 'timestamp'], unique=False)

    with op.batch_alter_table('message_attachments', schema=None) as batch_op:
        batch_op.alter_column('mime_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.alter_column('file_path',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    with op.batch_alter_table('llm_executions', schema=None) as batch_op:
        batch_op.drop_column('sequence_index')

    with op.batch_alter_table('message_thoughts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_thoughts_message_id'))

    op.drop_table('message_thoughts')
    # ### end Alembic commands ###