"""Remove agent_skills join table

Revision ID: ad6cbc26949c
Revises: 3bb9a7f3b1c6
Create Date: 2026-08-03 11:11:14.252976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad6cbc26949c'
down_revision = '3bb9a7f3b1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_skills')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    op.create_table('agent_skills',
    sa.Column('agent_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_name'], ['skills.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'skill_name')
    )
    # ### end Alembic commands ###
